export interface IStudent {

    id: number;
    studcode: number;
    studName: string;
    fatherName: string;
    motherName: string;
    class: string;
    gender: string;
    dateOfBirth: string;
    locationOfBirth: string;
    religion: string;
    fatherJob: string;
    address: string;
    streetName: string;
    area: string;
    state: boolean;
    fatherMobile: string;
    motherMobile: string;
    telephone: string;
    nationalityId: number;
    notes: string;
    // schoolEmail: string;
    // mobile: string;
    // photoFileName: string;
    // privateNotes: string;
    // remarks: string;
    // creatorUserId: number;
    // creationDate: Date;
    // modifiedUserId: number;
    // lastDateModified: Date;
    // isDeleted: boolean;
    // integrationId: string;
    // fatherWorkTelephone: string;
    // motherWorkTelephone: string;
    // areaId?: number;
    // fatherMobile: string;
    // motherMobile: string;
    // officialRegistrationDate?: Date;
    // officialRegistrationNumber: number;
    // firstNameAr: string;
    // fatherNationalIdnumber: string;
    // hasResponsible?: boolean;
    // responsibleName: string;
    // studentResponsibleRelationId?: number;
    // responsibleTelephone: string;
    // responsibleAddress: string;
    // responsibleMobile: string;

}